# Generated by Django 4.0.4 on 2022-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('optional_agreement', models.JSONField()),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
