# Generated by Django 4.0.4 on 2022-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_optional_agreement_optionalagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='optional_agreement',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='OptionalAgreement',
        ),
    ]
