# Generated by Django 4.0.2 on 2022-05-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.paymentmethod'),
        ),
    ]
