# Generated by Django 4.0.2 on 2022-05-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='optiona_existence',
            new_name='optional_existence',
        ),
    ]
